### ISSUE TITLE
scoring

### ISSUE THREAD

**Issue by pakratt0013** [skyboy/CobbleHaters#1]
+5 for destroying iron ingot
+2 for destroying gold ingot
+1 for destroying emerald

-1 for every 10 minutes playing (may need adjustment)

double positive score for defeating dragon, end round

**Comment by RyPeterson** [comment]
I dont know about what the devs are thinking, but last night during the stream I was thinking about how to do this. For the scoreboard display, I have seen other packs that have mods which adds a timer and in-game clock, so it might be worthwhile to look at that code if its available to implement the scoreboard. I hate chat-spams, so that might help cut down on that. 

For the destruction detection, I haven't looked into the API so I don't know the specifics. If Pak isn't seeking a stand-alone mod, I would suggest using the HQM to submit these items for detection and deletion.

**Comment by skyboy** [comment]
Implemented here: https://github.com/skyboy/Scoring
